# Generated by Django 6.1.1 on 2026-10-03 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_seats', models.PositiveIntegerField()),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('is_active', models.BooleanField(default=False)),
                ('is_allocation_complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='drops.drop')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drop_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('drop', 'user'), name='unique_user_per_drop')],
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField()),
                ('drop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='drops.drop')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('drop', 'seat_number'), name='unique_seat_per_drop')],
            },
        ),
    ]
