# Generated by Django 6.1.1 on 2026-10-03 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drop',
            name='allocation_started',
            field=models.BooleanField(default=False),
        ),
    ]
