# Generated by Django 6.1.1 on 2026-10-03 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='drops.entry')),
                ('seat', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='allocation', to='drops.seat')),
            ],
        ),
    ]
